name: CubeCubeBall
main: me.crylonz.CubeBall
version: 1.0.0
author: Crylonz, squi2rel
description: Play football in Minecraft
api-version: 1.16
commands:
  ccb:
    permission: cubecubeball.manage
    description: Control command
    usage: /ccb
permissions:
  cubecubeball.manage:
    description: Allows player to manage cubeball
    default: op
  cubecubeball.admin:
    description: Manage all match
    default: op