name: CubeCubeBall
main: me.crylonz.CubeBall
version: 1.0.0
author: Crylonz, squi2rel
description: Play football in Minecraft
api-version: 1.13
commands:
  ccb:
    description: Control command
    usage: /ccb
permissions:
  cubecubeball.manage:
    description: Allows player to manage cubeball
    default: op